# Configurações do Jekyll

# Pasta de origem
source: docs

# Configurações do GitHub Pages
remote_theme: primer
plugins:
  - jekyll-github-metadata

# Outras configurações opcionais

# Título do site
title: Meu Site

# Descrição do site
description: Descrição do meu site

# Tema do site
theme: jekyll-theme-primer
